[PHP]
; Memory
memory_limit = 512M
max_execution_time = 300
max_input_time = 300

; Upload
upload_max_filesize = 256M
post_max_size = 260M
max_file_uploads = 20

; OPcache
opcache.enable = 1
opcache.memory_consumption = 256
opcache.interned_strings_buffer = 16
opcache.max_accelerated_files = 20000
opcache.validate_timestamps = 1
opcache.revalidate_freq = 2
opcache.save_comments = 1

; Session
session.save_handler = redis
session.save_path = "tcp://redis:6379"

; Error handling
display_errors = Off
log_errors = On
error_reporting = E_ALL

; Date
date.timezone = Asia/Kolkata
